from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(622, 540)
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(10, 20, 591, 41))
        self.textEdit.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.textEdit.setObjectName("textEdit")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 60, 591, 471))
        self.tableWidget.setStyleSheet("gridline-color: rgb(170, 255, 127);\n"
"alternate-background-color: rgb(170, 255, 127);\n"
"border-bottom-color: rgb(170, 255, 127);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(170, 255, 127))
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(170, 255, 127))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(170, 255, 127))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(170, 255, 127))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(170, 255, 127))
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\SMT.1\\ALPRO G\\png-transparent-broccoli-vegetable-cauliflower-leaf-vegetable-food-grass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\SMT.1\\ALPRO G\\png-transparent-arrow-computer-icons-down-arrow-angle-2d-computer-graphics-green-thumbnail.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\SMT.1\\ALPRO G\\kisspng-filipino-cuisine-water-spinach-asian-cuisine-leaf-morning-glory-5afe72ab6d4e78.7025633915266249394477.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\SMT.1\\ALPRO G\\kisspng-division-subtraction-sign-mathematics-obelus-negative-money-cliparts-5a762f03039129.3712697915176947230146.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon3)
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("D:\\SMT.1\\ALPRO G\\carrot-png-5a21c005b1b8f3.250363361512161285728.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon4)
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("D:\\SMT.1\\ALPRO G\\kisspng-arrow-icon-up-arrow-transparent-png-5a77bcb44b9aa6.5964438415177965323097.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon5)
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("D:\\SMT.1\\ALPRO G\\transparent-eggplant-vegetable-purple-food-plant-5d6849f5cd4a88.3257814415671157658409.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon6)
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon3)
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("D:\\SMT.1\\ALPRO G\\kisspng-juice-food-eating-health-apple-apple-fruit-transparent-png-5a748186173281.061706731517584774095.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon7)
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon3)
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("D:\\SMT.1\\ALPRO G\\419-4197493_gambar-kartun-pisang-pisang-clipart-hd-png-download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon8)
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon3)
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("D:\\SMT.1\\ALPRO G\\watermelon-png-image-picture-download-5a35d8c7309967.7675305415134783431991.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon9)
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon1)
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("D:\\SMT.1\\ALPRO G\\png-clipart-fried-chicken-tandoori-chicken-pakistani-cuisine-pakora-jerk-seasoning-food-recipe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon10)
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon1)
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("D:\\SMT.1\\ALPRO G\\kisspng-fish-spice-flat-fish-5aa43cb28b5bf8.2805629915207128825708.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon11)
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon5)
        self.tableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("D:\\SMT.1\\ALPRO G\\kisspng-caridea-shrimp-condiment-lee-kum-kee-food-personalized-shrimp-platter-5a9cd8ae9e96a8.0946965815202285266496.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon12)
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon3)
        self.tableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 3, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(115)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(60)
        self.tableWidget.verticalHeader().setDefaultSectionSize(40)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(40, 490, 121, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(430, 490, 71, 31))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("D:\\SMT.1\\ALPRO G\\kisspng-check-mark-computer-icons-clip-art-green-check-mark-2-icon-5ab1d1c01cb222.3320573215216030081176.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon13)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 490, 71, 31))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("D:\\SMT.1\\ALPRO G\\kisspng-x-mark-check-mark-clip-art-wrong-sign-5b12e9983fd272.4809619715279661042614.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon14)
        self.pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(170, 490, 41, 31))
        self.spinBox.setObjectName("spinBox")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(510, 70, 81, 141))
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.85455pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; text-decoration: underline;\">Form Pemesanan Fresh Box</span></p></body></html>"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1."))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2."))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3."))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4."))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5."))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "6."))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "7."))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "8."))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "9."))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "10."))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Kode Produk"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Nama Produk"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Harga / Biji"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Stok tersedia"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Dialog", "SB"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Dialog", "Brokoli"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("Dialog", "9.000"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("Dialog", "KK"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("Dialog", "Kangkung"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("Dialog", "4.000"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("Dialog", "WTL"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("Dialog", "Wortel"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("Dialog", "20.000"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("Dialog", "TRG"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("Dialog", "Terong"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("Dialog", "7.000"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("Dialog", "APL"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("Dialog", "Apel"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("Dialog", "23.000"))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("Dialog", "PSG"))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("Dialog", "Pisang"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("Dialog", "12.000"))
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("Dialog", "SMK"))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("Dialog", "Semangka"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("Dialog", "25.000"))
        item = self.tableWidget.item(6, 3)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("Dialog", "AB"))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("Dialog", "Ayam Bumbu"))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("Dialog", "34.000"))
        item = self.tableWidget.item(7, 3)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("Dialog", "IB"))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("Dialog", "Ikan Bumbu"))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("Dialog", "32.000"))
        item = self.tableWidget.item(8, 3)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("Dialog", "UB"))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("Dialog", "Udang Bumbu"))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("Dialog", "48.000"))
        item = self.tableWidget.item(9, 3)
        item.setText(_translate("Dialog", "10"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.textEdit_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.85455pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Masukkan kode menu</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "Pesan"))
        self.pushButton_2.setText(_translate("Dialog", "Hapus"))
        self.plainTextEdit.setPlainText(_translate("Dialog", "Keterangan :\n"
"↑ Harga pasar naik\n"
"\n"
"↓ Harga pasar turun\n"
"\n"
"- Harga Rata-rata"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())